mysite/urls.py
from django.conf.urls import include,url
from django.contrib import admin
# from django.contrib.auth import views as auth_views
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^user/', include('user.urls')),
    # url(r'^logind/$', auth_views.login, {'template_name': 'login.html'}, name='login'),
    # url(r'^logoutd/$', auth_views.logout, name='logout'),
]

user/urls.py
from django.conf.urls import url

from . import views
app_name = 'user'
urlpatterns = [
     # ex: /login/
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^register/$', views.register, name='register'),
    url(r'^$', views.index, name='index'),
   
]

user/models.py
from django.db import models

# Create your models here.

user/forms.py
from django import forms
from django.contrib.auth import authenticate
from django.contrib.auth.models import User as Userobj

class LoginForm(forms.Form):
    username = forms.CharField( 
        max_length=254,
        widget=forms.TextInput(attrs={'class': "form-control"}),
    )
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class':"form-control"}))
    def clean(self):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')
        user = authenticate(username=username, password=password)
        if not user or not user.is_active:
            raise forms.ValidationError("Sorry, that login was invalid. Please try again.")
        return self.cleaned_data

    def login(self, request):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')
        user = authenticate(username=username, password=password)
        return user

class Contactform(forms.Form):
    username = forms.CharField(
        max_length=254,
        widget=forms.TextInput(attrs={'class': "form-control"}),
    )
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class':"form-control"}))
class RegisterForm(forms.Form):
    name = forms.CharField(
        max_length=254,
        widget=forms.TextInput(attrs={'class': "form-control"}),
    )
    email = forms.EmailField(  
        max_length=254,
        widget=forms.EmailInput(attrs={'class': "form-control"}),
    )
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'class':"form-control"}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'class':"form-control"}))

    def clean(self):
        name = self.cleaned_data.get('name')
        password = self.cleaned_data.get('password1')
        user = authenticate(username=username, password=password)
        if not user or not user.is_active:
            raise forms.ValidationError("Sorry, that login was invalid. Please try again.")
        return self.cleaned_data

    def register(self, request):
        name = self.cleaned_data.get('name')
        email = self.cleaned_data.get('email')
        password = self.cleaned_data.get('password1')
        user = Userobj.objects.create_user(name, email, password)
        user.save()
        return user

user/views.py
from django.http import Http404,HttpResponseRedirect
from django.shortcuts import render,get_object_or_404
from django.contrib.auth import  login  as auth_login
from django.contrib.auth import logout as auth_logout
from .forms import LoginForm,RegisterForm
# Create your views here.
##Login
def login(request):
    # if this is a POST request we need to process the form data
    if request.method == 'POST':       
        form = LoginForm(request.POST)
        if form.is_valid():          
           user = form.login(request)
           if user:
            auth_login(request, user)
            return HttpResponseRedirect("/user/")# Redirect to a success page.
           else:       
            # redirect to a new URL:
            return HttpResponseRedirect('/login/')
    # if a GET (or any other method) we'll create a blank form
    else:
        form = LoginForm()

    return render(request, 'login.html', {'form': form})

def index(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect('/user/login/')        
    return render(request, 'home.html', {})  

def logout(request):
    auth_logout(request)
    return HttpResponseRedirect('/user/login/')
##Registration
def register(request):
    # if this is a POST request we need to process the form data
    if request.method == 'POST':       
        form = RegisterForm(request.POST)
        if form.is_valid():          
           user = form.register(request)
           if user:
            auth_login(request, user)
            return HttpResponseRedirect("/user/")# Redirect to a success page.
           else:       
            # redirect to a new URL:
            return HttpResponseRedirect('/login/')
    # if a GET (or any other method) we'll create a blank form
    else:
        form = RegisterForm()

    return render(request, 'register.html', {'form': form})

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/font-awesome.min.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}" />
<title>{% block title %}My amazing site{% endblock %}</title>

</head>
<body>
    <!-- Static navbar -->
    <nav id="top-bar-nav" class="navbar navbar-default navbar-fixed-top">
    <div class="container navbar-inner ">
      <ul class="nav nav-pills pull-right">
                  {% if user.is_authenticated %}
                  <li>Welcome, {{ user.username }}.</li>
                  <li><a href="{% url 'user:logout'%}" class="btn btn-link" ><i class="fa fa-sign-out" aria-hidden="true"></i>Logout</a></li>
                  {% else %}
                      <li>Welcom quest,</li>
                      <li><a href="{% url 'user:logout'%}" class="btn btn-link" ><i class="fa fa-sign-in" aria-hidden="true"></i>Login</a></li>
                  {% endif %}           
          </ul>
    </div>
    </nav>
    <!-- Static navbar -->
    <nav id="middle-bar-nav"  class="navbar navbar-default navbar-static-top">
      
      <div class="container">
     
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#"><img src="{% static 'img/logo.png'%}"></a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <!--<li class="active"><a href="#"><i class="fa fa-home" aria-hidden="true"></i></a></li>
             <li><a href="#about">About</a></li>
            <li><a href="#contact">Contact</a></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="#">Action</a></li>
                <li><a href="#">Another action</a></li>
                <li><a href="#">Something else here</a></li>
                <li role="separator" class="divider"></li>
                <li class="dropdown-header">Nav header</li>
                <li><a href="#">Separated link</a></li>
                <li><a href="#">One more separated link</a></li>
              </ul>
            </li> -->
          </ul>
         
        </div><!--/.nav-collapse -->
      </div>
    </nav>


    <div class="container">

      <!-- Main component for a primary marketing message or call to action -->
      <div class="jumbotron">
      <h2>{% block head %}{% endblock %}</h2>
        {% block content %}{% endblock %}
         </div>
    </div><!-- /.container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="{% static 'js/jquery.min.js' %}"><\/script>')</script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

<!--     <div id="sidebar">
        {% block sidebar %}
        <ul>
            <li><a href="/">Home</a></li>
            <li><a href="/blog/">Blog</a></li>
        </ul>
        {% endblock %}
    </div> -->


</body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block title %}Login{% endblock %}

{% block content %}
  <h2>Home</h2>
{% endblock %}

templates/logged_out.html
{% extends 'base.html' %}

{% block title %}See you!{% endblock %}

{% block content %}
  <h2>Logged out</h2>
  <p>You have been successfully logged out.</p>
  <p><a href="{% url 'login' %}">Log in</a> again.</p>
{% endblock %}

templates/login.html
{% extends 'base.html' %}

{% block title %}Login{% endblock %}

{% block content %}
  <h2>Login</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Login</button>
  </form>
{% endblock %}

user/templates/login.html
{% extends "base.html" %}
{% block title %}Login{% endblock %}
{%block head %}Login{% endblock %}
{% block content %}
<!-- <h1>User Login</h1>
<form action="/your-name/" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit" />
</form> -->

{% if form.has_errors %}
<p>{{ login_message }}</p>
{% endif %}
<form method="post" action="{% url 'user:login' %}">
<p><label for="id_username">Username:</label>
{{ form.username }}</p>
<p><label for="id_password">Password:</label>
{{ form.password }}</p>
<input type="hidden" name="next" value="/" />
<input type="submit" class="btn btn-info" value="login" />
{% csrf_token %}
{% endblock %}

user/templates/register.html
{% extends "base.html" %}
{% block title %}Register{% endblock %}
{%block head %}Register{% endblock %}
{% block content %}

{% if form.has_errors %}
<p>{{ registration_message }}</p>
{% endif %}
<form method="post" action="{% url 'user:register' %}">
<p><label for="id_name">Name:</label>
{{ form.name }}</p>
<p><label for="id_email">Email:</label>
{{ form.email }}</p>
<p><label for="id_password1">Password:</label>
{{ form.password1 }}</p>
<p><label for="id_password2">Repeat Password:</label>
{{ form.password2 }}</p>
<input type="hidden" name="next" value="/" />
<input type="submit" class="btn btn-info" value="Submit" />
{% csrf_token %}
{% endblock %}